In [18]:
import numpy as np
import os.path 
n = 10
Grid_data = np.ones((n,n,n))
save_path = '/home/links/hm556/DCoding/DGitLab/DProject/inputs'


name_of_file = 'geom'

completeName = os.path.join(save_path, name_of_file+".in")         

file = open(completeName, "w")

file.write('0.00019999999999999998 0.00019999999999999998 0.00019999999999999998'+'\n')
file.write(f'{n} {n} {n} '+'\n')
for i in range(0,n):
    for j in Grid_data[i]:
        file.write('\n')
        for k in j:
            file.write(str(int(k))+' ')
    file.write('\n')
file.close()




In [24]:
n = 10
Grid_data = np.ones((n,n,n))*0
save_path = '/home/links/hm556/DCoding/DGitLab/DProject/inputs'

Grid_data[5,:,:] += 1
print(Grid_data[5,:,:])
name_of_file = 'heat'

completeName = os.path.join(save_path, name_of_file+".in")         

file = open(completeName, "w")


for i in range(0,n):
    for j in Grid_data[i]:
        file.write('\n')
        for k in j:
            file.write(str(int(k))+' ')
    file.write('\n')
file.close()



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
